### ISSUE TITLE
Cannot find module for alert.styl

### ISSUE THREAD

**Issue by AlwaysAwake** [schiehll/react-alert#4] opened 2016-01-17 17:55 UTC
Error: Cannot find module '!!./../../../node_modules/css-loader/index.js!./../../../node_modules/postcss-loader/index.js!./../../../node_modules/stylus-loader/index.js!./alert.styl'

I'm still getting this error when I include your module and build my project. I know this is the possibly duplicate of #2, but It is not solved yet. How can I fix it? Could you mind including your modules inside my project and build with my components? Of course, I will make clear this component is 100% your creation.

**Comment by dherran** [comment] 2016-05-02 16:13
This happens if you are not using webpack. The developer compiled the dist using a webpack dependency which breaks on other environments.

I would suggest moving the styles to a standard SASS file and not bundling the styles into webpack loaders. Styles should be handled separately and should be entirely optional.

**Comment by mclapa** [comment] 2016-09-07 16:43
Yeah it's unfortunate but I'm running into this problem. In my case I'm using React and our file structure does not match his

`Error: Cannot find module '!!./../../../node_modules/css-loader/index.js!./../../../node_modules/postcss-loader/index.js!./../../../node_modules/stylus-loader/index.js!./alert.styl'`

**Comment by vasanth-mahendran** [comment] 2016-09-16 21:05
Does any one found a solution for this problem?

**Comment by saward** [comment] 2016-09-20 06:15
I have been able to get it semi-working by just commenting out the relevant lines inside node_modules/react-alert/dist/alert.js:

`		if(!content.locals) {
			// module.hot.accept("node_modules/react-alert/dev/assets/alert.styl", function() {
				// var newContent = require("node_modules/react-alert/dev/assets/alert.styl");
				// if(typeof newContent === 'string') newContent = [[module.id, newContent, '']];
				// update(newContent);
			// });
		}`

I'm trying to include alert.styl because the styling of the alert isn't quite right, but I'm not sure if it's because of this change or just some other option I need to set.

**Comment by saward** [comment] 2016-09-20 07:18
I can confirm that commenting out these lines allowed me to run it.  I assume that this will prevent providing another style, but I'm not sure.

The remaining issue I had was due to another conflicting css rule from something separate.

**Comment by MeXaaR** [comment] 2017-03-25 10:22
Actually, it was the path to alert.styl. it wasn't the correct one,
I made a corrected fork [here](https://github.com/MeXaaR/mx-react-toaster)

hope it helps

**Comment by schiehll** [comment] 2017-05-06 01:22
Should be fixed with the v2 release. A lot of issues here are really old, as the project was unmaintained, so I will close all issues. Feel free to ask to open it again if the issue persist after v2 update.

**Closed by schiehll** 2017-05-06 01:22 UTC
