### ISSUE TITLE
ract-alert doesn't work with ssr

### ISSUE THREAD

**Issue by stelro** [schiehll/react-alert#75] opened 2018-03-29 17:41 UTC
Hello, seems that react-alert doesn't work with SSR and react 16.2.0! Any suggestion? 
It seems that whatever I wrap in AlertProvider  it doesn't renderToString.

**Comment by schiehll** [comment] 2018-04-01 00:33
Hey @stelro thank you for open the issue!

I think the problem is now fixed in the latest release, please give it a try and feel free to reopen it if the problem persist.

The new version uses the new context api so you will need React v16.3.0 to be able to use it.

**Closed by schiehll** 2018-04-01 00:33 UTC
