### ISSUE TITLE
Upgrade version react, react - dom

### ISSUE THREAD

**Issue by huukuntp1** [schiehll/react-alert#82] opened 2018-05-17 05:11 UTC
Hello, 
I use **react -alert**, but the problem it not working because version react and react-dom, after i upgrade version follows npmjs:
<code>
"prop-types": "^15.6.0"
"react": "^16.3.0"
"react-dom": "^16.3.0"
"react-transition-group": "^2.3.0"
</code>
This not working, I try update:
<code>
"prop-types": "15.6.0"
"react": "16.3.0"
"react-dom": "16.3.0"
"react-transition-group": "2.3.0"
</code>
and this working,

Let me know this problem ?

Regards

**Comment by schiehll** [comment] 2018-05-17 07:04
Hi @huukuntp1 

Since the caret prefix only means that the dependency can be updated to any not major new version (you can read more about it [here](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004)), I'm pretty sure that it is working as you can see [here](https://codesandbox.io/s/l2mo430lzq) (check the dependencies).

I don't know, maybe try to remove the `node_modules` folder and install the dependencies again?

I will close the issue since it looks like it's not a problem in this lib, but feel free to ask me to reopen it if you can come up with a repository that reproduces the issue.

**Closed by schiehll** 2018-05-17 07:04 UTC
